- name: copy catalogue service 
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: demon reload 
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue 
  ansible.builtin.service:
    name: catalogue
    enabled: yes
    state: started
    